### ISSUE TITLE
How do I run the benchmarks?

### ISSUE THREAD

**Issue by SteveDiamond** [sergiocallegari/PyDSM#4]
I'm comparing cvxpy with my new preprocessor for cvxopt against the other solvers. But I don't know how to run the bench_ntf_fir_weighting.py file.

**Comment by sergiocallegari** [comment]
Hi Steve,

All the benchmarks that are currently available can be run by `import pydsm` and then `pydsm.bench()`

Benchmarking framework is that of numpy

Benchmarks are probably a bit incomplete as of today.
